<!-- Secondary Random vlogs (pick from all but the latest) -->
<div class="clearfix vlogsAdditionalPanel vlogBlock">
    <header>
        <h3><i class="icon-video"></i>Additional Vlogs</h3>
    </header>
    <?php print views_embed_view('videos', 'block_additional'); ?>

    <footer>
        <a class="buttonA" href="#">
            sign up for Vlog<i class="icon-pen"></i>
        </a>
    </footer>
</div>