
<nav class="clearfix swContainer footer">
    <!--If item doesn't have dropdown add it to the first list.-->
    <ul class="col-sm-3">
                <li>
                    <a href="#" title="curriculum decisions home page">home</a>
                </li>
                <li>
                    <a href="#" title="curriculum decisions home page">contact</a>
                </li>
    </ul>


            <ul class="col-sm-3">
                <li>
                    <a href="#" title="curriculum decisions home page">curriculum mapping</a>
                </li>
                <li>
                    <a href="#" title="curriculum decisions home page">overview</a>
                </li>
                <li>
                    <a href="#" title="curriculum decisions home page">mapping model</a>
                </li>
                <li>
                    <a href="#" title="curriculum decisions home page">mapping focuses</a>
                </li>
                <li>
                    <a href="#" title="curriculum decisions home page">mapping and change</a>
                </li>
            </ul>
            <ul class="col-sm-3">
                <li>
                    <a href="#" title="curriculum decisions home page">curriculum design</a>
                </li>
                <li>
                    <a href="#" title="curriculum decisions home page">overview</a>
                </li>
                <li>
                    <a href="#" title="curriculum decisions home page">mapping model</a>
                </li>
                <li>
                    <a href="#" title="curriculum decisions home page">mapping focuses</a>
                </li>
                <li>
                    <a href="#" title="curriculum decisions home page">mapping and change</a>
                </li>
            </ul>
</nav>