
<nav class="primary">
    <ul class="swContainer">


            <li>
                <i class="icon-home-outline"></i>

                <a href="#" title="curriculum decisions home page">home</a>


            </li>


            <li>
                <i class="icon-map"></i>

                <a href="#" title="curriculum decisions home page">curriculum mapping</a>

                    <div class="dropContainer large">

                        <ul class="childLinks">
                                <li>
                                    <a href="#" title="curriculum decisions home page">overview</a>
                                </li>
                                <li>
                                    <a href="#" title="curriculum decisions home page">mapping model</a>
                                </li>
                                <li>
                                    <a href="#" title="curriculum decisions home page">mapping focuses</a>
                                </li>
                                <li>
                                    <a href="#" title="curriculum decisions home page">mapping and change</a>
                                </li>
                        </ul>


                    </div>



            </li>


            <li>
                <i class="icon-diamond"></i>

                <a href="#" title="curriculum decisions home page">curriculum design</a>

                    <div class="dropContainer large">

                        <ul class="childLinks">
                                <li>
                                    <a href="#" title="curriculum decisions home page">overview</a>
                                </li>
                                <li>
                                    <a href="#" title="curriculum decisions home page">mapping model</a>
                                </li>
                                <li>
                                    <a href="#" title="curriculum decisions home page">mapping focuses</a>
                                </li>
                                <li>
                                    <a href="#" title="curriculum decisions home page">mapping and change</a>
                                </li>
                        </ul>


                    </div>



            </li>


            <li>
                <i class="icon-mail"></i>

                <a href="#" title="curriculum decisions home page">contact</a>


            </li>



    </ul>
</nav>